app = "p3-preditor-tickets"

[build]
  dockerfile = "docker-compose.yml"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    restart_limit = 3